version: '3'
services:
  mariadb:
    image: my-golang-db-app
    build: ./db.dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=M@utauaja982
    restart: always

  golang:
    image: my-golang-app
    build: ./golang.dockerfile
    ports:
      - 3303:8090
    restart: always
    links: 
      - mariadb
    depends_on:
      - "mariadb"
